import { Footer, Dropdown } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { menuItems } from '@/data/data' 

export const metadata: Metadata = {
  title: 'Taxiar || The Best Way To Get Around Town',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">  
      <> 
      <div className=" justify-center  bg-gray-100">
      <Dropdown menuItems={menuItems} />
      </div>
        {children}
        
        <Footer />
        </>     
        </body>
    </html>
  )
}
